---
website:
  vars:
    ansible_python_interpreter: auto_legacy_silent
    domains:
      - uahelp2.mjwcodr.de 
    repo: 
      name: website-a
      url: https://github.com/ua-help-website/website-a.git
      location: /srv/www/website-a/
      
    email: matthias.wuensch175@gmail.com
  hosts:
    website-a:
      ansible_host: 85.214.24.162
